import request from '../utils/request'

export const createFamily = (payload) => request.post('/families', payload)
export const joinFamily = (payload) => request.post('/families/join', payload)
export const getFamilies = (params) => request.get('/families', { params })
export const getFamilyMembers = (familyId) => request.get(`/families/${familyId}/members`)
export const getFamilyBoard = (familyId) => request.get(`/families/${familyId}`)
export const getFamilyDashboard = (familyId) => request.get(`/families/${familyId}/dashboard`)
export const getAbnormalToday = (familyId) => request.get(`/families/${familyId}/abnormal-today`)
export const getHealthIndex = (familyId) => request.get(`/families/${familyId}/health-index`)
export const getMetricTrends = (familyId, params) => request.get(`/families/${familyId}/metrics/trends`, { params })
export const getStatusDistribution = (familyId) => request.get(`/families/${familyId}/status/distribution`)
export const getRecentEvents = (familyId) => request.get(`/families/${familyId}/events/recent`)
export const updateFamily = (familyId, payload) => request.put(`/families/${familyId}`, payload)
export const regenerateInviteCode = (familyId) => request.post(`/families/${familyId}/invite/regenerate`)
export const updateMember = (familyId, memberId, payload) => request.put(`/families/${familyId}/members/${memberId}`, payload)
export const removeMember = (familyId, memberId) => request.delete(`/families/${familyId}/members/${memberId}`)
export const setDataShare = (familyId, shareToFamily) => request.post(`/families/${familyId}/share?shareToFamily=${shareToFamily}`)
export const bindFamilyDoctor = (familyId, payload) => request.post(`/families/${familyId}/doctor/bind`, payload)
export const getFamilyDoctor = (familyId) => request.get(`/families/${familyId}/doctor`)
export const getDoctorView = (familyId, useAi = false) => request.get(`/families/${familyId}/doctor-view`, { params: { useAi } })
export const unbindFamilyDoctor = (familyId) => request.delete(`/families/${familyId}/doctor`)
export const getDoctorFamilies = () => request.get('/doctor/families')
